### ISSUE TITLE
 Add MIDI on 32u4?

### ISSUE THREAD

**Issue by naught101** [NicoHood/HID#2]
I see that this is already on your todo list. How hard would this be? What would be required?

**Comment by NicoHood** [comment]
More information here:
https://github.com/NicoHood/HID/wiki/Midi-Support

**Comment by NicoHood** [comment]
Try this:
https://github.com/rkistner/arcore

**Comment by NicoHood** [comment]
Well,
now available for testing:
https://github.com/NicoHood/HID/tree/Midi-Test

Only works with 32u4 (leonardo/micro) and is activated by default. Select one of the USB-Cores, but no HID will work.
I really need feedback about this, I just made it recognize by the PC but had no chance to test it yet.

**Comment by ayildirim** [comment]
I guess MIDI wont work with Arduino UNO yet?

**Comment by NicoHood** [comment]
No it wont. Simply because the 16u2 only has 4 USB Endpoints. Serial uses 3, Midi 2 and HID1. The 32u4 has 6 Endpoints. (However Midi and HID dont play well together). And Right now I cannot deactivate the Serial device, due to bad USB-Core code organization.

You can try the midi firmwares from other people and upload them via avrdude. You can still switch forth and back to your Hoodloader bootloader to load new sketched to the 328. Links can be found in the wiki. Similar firmwares will be provided later.

**Comment by CaptainCredible** [comment]
Has this been tested yet ? I will try it as soon as I have a chance

**Comment by NicoHood** [comment]
No I paused working on this, because I need feedback.
Tell me if it works and I will make a proper IDE integration.

Also there is currently some work, also for MIDI, going on here:
https://github.com/arduino/Arduino/pull/3304

**Comment by NicoHood** [comment]
Midi USB is now in the current hourly IDE build:
https://github.com/arduino/Arduino/wiki/PluggableUSB-and-PluggableHID-howto
arduino/Arduino#3304

**Comment by CaptainCredible** [comment]
Woooooooooot!

**Comment by naught101** [comment]
Thanks Nico. I guess this can be closed then?

**Comment by NicoHood** [comment]
More or less. The HID Project Midi example is just a dev state. And I will give up the HID Project 2.2 and 2.3 dev anyways. Because the new solution is just better.

HID Project 2.4 will then become a library instead of a core (which is better anyways) and only include the Consumer, System and Gamepad files.

I will keep the issue still open for now as a reminder it is not fixed in the current version. If its not needed later, I'll close it then.

**Comment by NicoHood** [comment]
https://github.com/arduino-libraries/MIDIUSB

**Comment by NicoHood** [comment]
Now closing since the dev branch is up to date with IDE 1.6.6 and Midi USB is now available as (half?) official library

**Comment by naught101** [comment]
Finally built that Arduino Micro USB device that I was wanting to (actually, it's a completely different one, but more useful for me now):

![midi controller](https://cloud.githubusercontent.com/assets/167164/23099194/44f92526-f6b5-11e6-860b-1a3c5e34ac7c.png)

Works pretty nicely with [really simple code](https://github.com/naught101/midi_knobs/blob/master/midi_knobs.ino). It's not quite finished yet ) want to add some buttons (in the mail, hopefully), and replace that dodgy fader knob ;), but it is already super useful.

Thanks heaps for your work on this, Nico, really appreciated!

**Comment by NicoHood** [comment]
Great! Thanks for sharing your feedback. Happy coding :)
