### ISSUE TITLE
IDE version check does not work with Arduino-Makefile

### ISSUE THREAD

**Issue by eharvester** [NicoHood/HID#219]
./local-libs/NicoHoodHID/src/HID-Project.h:31:2: error: #error HID Project requires Arduino IDE 1.6.7 or greater. Please update your IDE.
 #error HID Project requires Arduino IDE 1.6.7 or greater. Please update your IDE.

I have 1.8.12, Arduino-Makefile extracts "1812" 
HID-Project.h expects equal or greater than "10607"

I'm not sure which one is the correct integer interpretation for the IDE version number.

**Comment by matthijskooijman** [comment]
This is a bug in Arduino-Makefile I think. Since Arduino 1.6.0, the format has changed from 1 digit  to 2 digits per component, so 1.8.12 should be `-DARDUINO=10812`. See https://github.com/arduino/arduino-cli/blob/master/docs/platform-specification.md#global-predefined-properties for the official reference (`runtime.ide.version`).

**Comment by eharvester** [comment]
Thanks for clarification.
