### ISSUE TITLE
Error while trying compile IRrecvDemo

### ISSUE THREAD

**Issue by Shmuel930** [NicoHood/HID#80]
Hi . so im using IRremote library 

with this simple code

```
#include <IRremote.h>

int RECV_PIN = 11;

IRrecv irrecv(RECV_PIN);

decode_results results;

void setup()
{
  Serial.begin(9600);
  irrecv.enableIRIn(); // Start the receiver
}

void loop() {
  if (irrecv.decode(&results)) {
    Serial.println(results.value, HEX);
    irrecv.resume(); // Receive the next value
  }
  delay(100);
}
```

but im getting this error

"Error compiling for board HoodLoader2 16u2."

what's seems to be the problem? (i tried to compile the ImporvedKeybord code and its working very well. but other codes that work before are not working anymore, i want to mix a IRremote and ImporveKeyboard toghter.

is there anyway to do it ?

**Comment by NicoHood** [comment]
This is a Hoodloader2 related issue, not HID project.
This error is causes by the ir library that you are using, because it has not pin defined to read the data (it uses timers that are only available on a few pins).
You can use my IRLRemote library instead (see dev2 branch for latest code):
https://github.com/NicoHood/IRLremote
